### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by JamesHDuffield** [aaron-edwards/krpc-js#1]
Hi Aaron,

Not familiar with nx-cloud but I can see that your access token is in the nx.json configuration. Just making sure this was meant to be exposed rather than a CI environment variable.

https://nx.dev/nx-cloud/account/access-tokens

**Comment by aaron-edwards** [comment]
Interesting, this was set up automatically from the nx generator. Looking at some [issues](https://github.com/nrwl/nx/issues/3649) it might be a read/write token which makes me feel quite uncomfortable with this library.

Luckily this is just a project I am using to get familiar with, so nothing too sensitive. But still want to look at it (I am probably not going to use nx for this going forward anyway) 

Thanks for pointing it our
